[project]
name = "pal-radiators-inventory"
version = "0.1.0"
requires-python = "==3.11.*"
description = "Streamlit app for PAL Radiators inventory intelligence"

[tool.uv]
# uv reads project.requires-python; this stanza is here for clarity
